name: BUILD_3GX

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pablomk7/libctrpf:0.8.0
    
    steps:
      - uses: actions/checkout@v4

      - name: 作る
        run: make
  
      - name: アップロード
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ./
