name: BUILD 3GX

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.8.0

    steps:
    - uses: actions/checkout@v2
      
    - name: TUKURU
      run: make
      
    - name: AGERU
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: ./
